---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
    - rvm: 2.3.0
      env: PUPPET_GEM_VERSION="~> 4.2.0" FUTURE_PARSER="yes"
notifications:
  email: false
